version: "3.7"

services:
  client:
    build: ./client
    command: npm run dev
    volumes:
      - ./client:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      BASE_URL: "http://localhost:5000"
    depends_on:
      - api
  api:
    build: ./api
    command: air -c .air.toml
    volumes:
      - ./api/:/usr/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  #     depends_on:
  #         - db
  # db:
  #     image: postgres:12-alpine
  #     volumes:
  #         - postgres_data:/var/lib/postgresql/data/
  #     environment:
  #         - POSTGRES_USER=flask_service
  #         - POSTGRES_PASSWORD=flask_service
  #         - POSTGRES_DB=flask_service_dev
# volumes:
# postgres_data:
