version: "3.7"

services:
  client:
    build: ./client
    command: npm run dev
    volumes:
      - ./client:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      BASE_URL: "http://localhost:5000"
    depends_on:
      - api
  api:
    build: ./api
    command: air -c .air.toml
    volumes:
      - ./api/:/usr/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
