version: "3.7"

services:
  # client:
  #   build: ./client
  #   command: npm run dev
  #   volumes:
  #     - ./client:/usr/app/
  #     - /usr/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./.env.dev
  #   environment:
  #     PORT: 3000
  #   depends_on:
  #     - api
  api:
    build: ./api
    command: air -c .air.toml
    volumes:
      - ./api/:/usr/app
      - ./api/:/go/src/api
      - ./api/:/usr/local/go/src/api
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    links:
      - mongodb
    environment:
      PORT: 5000
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: rootpassword
      MONGODB_URL: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: my_library_app
    depends_on:
      - mongodb
    networks:
      - mongodb-compose-network
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: my_library_app
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongodb-compose-network

volumes:
  mongodb_data_container:

networks:
  mongodb-compose-network:
      driver: bridge
